name: openhiit_audioplayers_darwin
description: iOS and macOS implementation of audioplayers, a Flutter plugin to play multiple audio files simultaneously
version: 1.0.6
homepage: https://github.com/a-mabe/openhiit_audioplayers
repository: https://github.com/a-mabe/openhiit_audioplayers/tree/master/packages/audioplayers_darwin

flutter:
  plugin:
    implements: audioplayers
    platforms:
      ios:
        pluginClass: SwiftAudioplayersDarwinPlugin

dependencies:
  audioplayers_platform_interface: ^7.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^1.0.0
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.13.0'

